task :default => :test

def run path, verbose = false
  output = `time sml #{path} < /dev/null`

  if output =~ /= false|hidden-value/ then
    puts "FAIL"
    puts
    puts output
    exit 1
  elsif verbose
    puts output
  end
end

task :test do
  run "*.sml"
end

task :slow do
  Dir["*.sml"].each do |path|
    puts path
    run path
    puts
  end
end

task :run do
  run ENV["F"], :verbose
end

task :clean do
  rm_f Dir["*~"]
end
