#!/usr/bin/env racket

#lang racket/base

(require "run-with-lang.rkt")

(for ([arg (in-vector (current-command-line-arguments))])
  (when (file-exists? arg)
    (run-with-lang (open-input-file arg) 'basic)))
